spring.application.name=OkaGaka

# Server encoding settings
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# PostgreSQL DB connection settings
spring.datasource.url=jdbc:postgresql://${RDS_HOST}:${RDS_PORT}/${RDS_NAME}
spring.datasource.username=${RDS_USER}
spring.datasource.password=${RDS_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# AWS settings
cloud.aws.region.static=${AWS_REGION}
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
cloud.aws.s3.bucket=${S3_BUCKET}

FRONTEND_ORIGIN=${FRONTEND_ORIGIN}

# TMAP
tmap.appKey=${TMAP_KEY}

# OpenWeatherMap
openweathermap.apiKey = ${WEATHER_KEY}

# OpenAI API
openai.apiKey = ${OPENAI_KEY}


# jwt
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# STT
GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
logging.level.com.google=DEBUG
logging.level.io.grpc=DEBUG

grpc.netty.shaded.io.netty.transport.noNative=true
io.netty.transport.noNative=true
# ?? ?? Caused by: java.lang.IllegalStateException: Only supported on Linux ERROR ??? -> ??? LINUX?? ???? ???? ??~~


# JPA settings

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate logging level
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type=trace

# Timezone settings
spring.jackson.time-zone=Asia/Seoul
